spring:
  application:
    name: inspection
  # 数据库配置
  datasource:
    name: inspection
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.76.245.176:3306/inspection?useSSL=false&serverTimezone=GMT%2B8
    # url: jdbc:mysql://localhost:3306/inspection?useSSL=false&serverTimezone=GMT%2B8
    username: root
    # password: root
    password: Yezhuhong1307404!
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # 文件上传的大小配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # 访问本地静态资源文件
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:/home/resources/
    # static-locations: file:/E:/inspection/
#  mvc:
#    view:
#      prefix: /
#      suffix: .html
# 端口号配置
server:
 port: 8090
# ssl:
#   key-store: classpath:server.keystore
#   key-store-password: yezhuhong1307404
#   key-alias: tomcat
#   enabled: true
#   key-store-type: PKCS12
#   ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
#   key-store: classpath:www.yezhuhongblog.com.pfx
#   key-store-password: nY0v8tz1
#   key-store-type: PKCS12

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhuhong.inspection.model

# Swagger API
swagger:
 enable: true

# 日志配置
logging:
  path: logs
  level:
    root: info
    com.zhuhong.inspection: debug

# upload_path: E:/inspection/
upload_path: /home/resources/

http_url: https://www.yezhuhongblog.com