spring:
  application:
    name: inspection
  #  ˝æ›ø‚≈‰÷√
  datasource:
    name: inspection
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inspection?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#  mvc:
#    view:
#      prefix: /
#      suffix: .html
# ∂Àø⁄∫≈≈‰÷√
server:
 port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhuhong.inspection.model

# Swagger API
swagger:
 enable: true

# »’÷æ≈‰÷√
logging:
  path: logs
  level:
    root: info
    com.zhuhong.inspection: debug